# This file was initially generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer. Thank you for the base
# However the classes were defined seperately by me (PhantomData87) to be used in a productive and easier to understand way.


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

class app():
    def __init__(self, canvas):
        # Using the global object
        self.canvas = canvas
        # App background
        self.canvas.place(x = 0, y = 0)
        self.canvas.create_rectangle(
            0.0,
            0.0,
            1440.0,
            985.0,
            fill="#231F1F",
            outline="")


        # Seperator 2
        self.canvas.create_rectangle(
            260.0,
            50.0,
            1440.0,
            60.0,
            fill="#524C4C",
            outline="")

        # Seperator 1
        self.canvas.create_rectangle(
            0.0,
            985.0,
            1440.0,
            990.0,
            fill="#514B4B",
            outline="")

class textLoader():
    def __init__(self, canvas):
        # Using the global object
        self.canvas = canvas
        # Word counter background rectangle
        self.canvas.create_rectangle(
            0.0,
            990.0,
            1440.0,
            1024.0,
            fill="#2F2828",
            outline="")

        # Character counter
        self.canvas.create_text(
            1255.0,
            1000.0,
            anchor="nw",
            text="Characters:",
            fill="#928E8E",
            font=("Inter Bold", 12 * -1)
        )

        # Word counter
        self.canvas.create_text(
            1140.0,
            1001.0,
            anchor="nw",
            text="Words:",
            fill="#928E8E",
            font=("Inter Bold", 12 * -1)
        )

        # Top rectangle background for Current file/paragraph
        self.canvas.create_rectangle(
            30.0,
            20.0,
            1440.0,
            50.0,
            fill="#413535",
            outline="")

        # Main rectangle background for text 
        self.canvas.create_rectangle(
            30.0,
            60.0,
            1440.0,
            985.0,
            fill="#494545",
            outline="")

        # Top right button 1
        button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))
        button_1 = Button(
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_1 clicked"),
            relief="flat"
        )
        button_1.place(
            x=1400.0,
            y=20.0,
            width=30.0,
            height=30.0
        )

        # Top right button 2
        button_image_2 = PhotoImage(
            file=relative_to_assets("button_2.png"))
        button_2 = Button(
            image=button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_2 clicked"),
            relief="flat"
        )
        button_2.place(
            x=1360.0,
            y=20.0,
            width=30.0,
            height=30.0
        )

        # Simple file icon
        image_image_1 = PhotoImage(
            file=relative_to_assets("image_1.png"))
        image_1 = self.canvas.create_image(
            275.0,
            35.0,
            image=image_image_1
        )

        # Main file/paragraph loader
        entry_image_1 = PhotoImage(
            file=relative_to_assets("entry_1.png"))
        entry_bg_1 = self.canvas.create_image(
            839.5,
            527.5,
            image=entry_image_1
        )
        entry_1 = Text(
            bd=0,
            bg="#494646",
            highlightthickness=0
        )
        entry_1.place(
            x=504.0,
            y=70.0,
            width=671.0,
            height=913.0
        )

        # Current file/Paragraph being viewed
        self.canvas.create_text(
            310.0,
            25.0,
            anchor="nw",
            text="Paragraph/File",
            fill="#FFFFFF",
            font=("Inter Bold", 16 * -1)
        )

class sidebar():
    def __init__(self, canvas):
        # Using the global object
        self.canvas = canvas
        # Sidebar background
        self.canvas.create_rectangle(
            0.0,
            50.0,
            30.0,
            985.0,
            fill="#302828",
            outline="")

        # Bottom sidebar button
        button_image_3 = PhotoImage(
            file=relative_to_assets("button_3.png"))
        button_3 = Button(
            image=button_image_3,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_3 clicked"),
            relief="flat"
        )
        button_3.place(
            x=0.0,
            y=945.0,
            width=30.0,
            height=30.0
        )

        button_image_4 = PhotoImage(
            file=relative_to_assets("button_4.png"))
        button_4 = Button(
            image=button_image_4,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_4 clicked"),
            relief="flat"
        )
        button_4.place(
            x=0.0,
            y=905.0,
            width=30.0,
            height=30.0
        )

        button_image_5 = PhotoImage(
            file=relative_to_assets("button_5.png"))
        button_5 = Button(
            image=button_image_5,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_5 clicked"),
            relief="flat"
        )
        button_5.place(
            x=0.0,
            y=865.0,
            width=30.0,
            height=30.0
        )

        # Top sidebar buttons
        button_image_6 = PhotoImage(
            file=relative_to_assets("button_6.png"))
        button_6 = Button(
            image=button_image_6,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_6 clicked"),
            relief="flat"
        )
        button_6.place(
            x=0.0,
            y=220.0,
            width=30.0,
            height=30.0
        )

        button_image_7 = PhotoImage(
            file=relative_to_assets("button_7.png"))
        button_7 = Button(
            image=button_image_7,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_7 clicked"),
            relief="flat"
        )
        button_7.place(
            x=0.0,
            y=180.0,
            width=30.0,
            height=30.0
        )

        button_image_8 = PhotoImage(
            file=relative_to_assets("button_8.png"))
        button_8 = Button(
            image=button_image_8,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_8 clicked"),
            relief="flat"
        )
        button_8.place(
            x=0.0,
            y=140.0,
            width=30.0,
            height=30.0
        )

        button_image_9 = PhotoImage(
            file=relative_to_assets("button_9.png"))
        button_9 = Button(
            image=button_image_9,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_9 clicked"),
            relief="flat"
        )
        button_9.place(
            x=0.0,
            y=100.0,
            width=30.0,
            height=30.0
        )

        button_image_10 = PhotoImage(
            file=relative_to_assets("button_10.png"))
        button_10 = Button(
            image=button_image_10,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_10 clicked"),
            relief="flat"
        )
        button_10.place(
            x=0.0,
            y=60.0,
            width=30.0,
            height=30.0
        )

class tabOptions():
    def __init__(self, canvas):
        # Using the global object
        self.canvas = canvas

        # Tab 3 option background
        self.canvas.create_rectangle(
            506.0,
            50.0,
            730.0,
            985.0,
            fill="#403434",
            outline="")
    
        # Tab 2 option background
        self.canvas.create_rectangle(
            270.0,
            50.0,
            494.0,
            985.0,
            fill="#403434",
            outline="")
        # Entry input tab 2 option background
        self.canvas.create_rectangle(
            277.0,
            99.0,
            489.0,
            119.0,
            fill="#332626",
            outline="")
        # Entry input tab 2 option
        entry_image_2 = PhotoImage(
            file=relative_to_assets("entry_2.png"))
        entry_bg_2 = self.canvas.create_image(
            375.5,
            109.0,
            image=entry_image_2
        )
        entry_2 = Entry(
            bd=0,
            bg="#332626",
            highlightthickness=0
        )
        entry_2.place(
            x=277.0,
            y=99.0,
            width=197.0,
            height=18.0
        )
        # Clear text tab option 2
        button_image_11 = PhotoImage(
            file=relative_to_assets("button_11.png"))
        button_11 = Button(
            image=button_image_11,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_11 clicked"),
            relief="flat"
        )
        button_11.place(
            x=474.0,
            y=102.0,
            width=14.0,
            height=14.0
        )
        # Tab option 2 buttons
        button_image_12 = PhotoImage(
            file=relative_to_assets("button_12.png"))
        button_12 = Button(
            image=button_image_12,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_12 clicked"),
            relief="flat"
        )
        button_12.place(
            x=447.0,
            y=60.0,
            width=30.0,
            height=30.0
        )
        button_image_13 = PhotoImage(
            file=relative_to_assets("button_13.png"))
        button_13 = Button(
            image=button_image_13,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_13 clicked"),
            relief="flat"
        )
        button_13.place(
            x=407.0,
            y=60.0,
            width=30.0,
            height=30.0
        )
        button_image_14 = PhotoImage(
            file=relative_to_assets("button_14.png"))
        button_14 = Button(
            image=button_image_14,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_14 clicked"),
            relief="flat"
        )
        button_14.place(
            x=367.0,
            y=60.0,
            width=30.0,
            height=30.0
        )
        button_image_15 = PhotoImage(
            file=relative_to_assets("button_15.png"))
        button_15 = Button(
            image=button_image_15,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_15 clicked"),
            relief="flat"
        )
        button_15.place(
            x=327.0,
            y=60.0,
            width=30.0,
            height=30.0
        )
        button_image_16 = PhotoImage(
            file=relative_to_assets("button_16.png"))
        button_16 = Button(
            image=button_image_16,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_16 clicked"),
            relief="flat"
        )
        button_16.place(
            x=287.0,
            y=60.0,
            width=30.0,
            height=30.0
        )
        # Tab option 2 GUI lines
        self.canvas.create_rectangle(
            276.0,
            129.0,
            287.0,
            130.0,
            fill="#8B8585",
            outline="")
        self.canvas.create_rectangle(
            296.0,
            129.0,
            307.0,
            130.0,
            fill="#8B8585",
            outline="")
        self.canvas.create_rectangle(
            316.0,
            129.0,
            327.0,
            130.0,
            fill="#8B8585",
            outline="")
        self.canvas.create_rectangle(
            336.0,
            129.0,
            347.0,
            130.0,
            fill="#8B8585",
            outline="")
        self.canvas.create_rectangle(
            356.0,
            129.0,
            367.0,
            130.0,
            fill="#8B8585",
            outline="")
        self.canvas.create_rectangle(
            376.0,
            129.0,
            387.0,
            130.0,
            fill="#8B8585",
            outline="")
        self.canvas.create_rectangle(
            396.0,
            129.0,
            407.0,
            130.0,
            fill="#8B8585",
            outline="")
        self.canvas.create_rectangle(
            416.0,
            129.0,
            427.0,
            130.0,
            fill="#8B8585",
            outline="")
        self.canvas.create_rectangle(
            416.0,
            129.0,
            427.0,
            130.0,
            fill="#8B8585",
            outline="")
        self.canvas.create_rectangle(
            436.0,
            129.0,
            447.0,
            130.0,
            fill="#8B8585",
            outline="")
        self.canvas.create_rectangle(
            456.0,
            129.0,
            467.0,
            130.0,
            fill="#8B8585",
            outline="")
        self.canvas.create_rectangle(
            476.0,
            129.0,
            487.0,
            130.0,
            fill="#8B8585",
            outline="")
        # Tab option 1 background
        self.canvas.create_rectangle(
            36.0,
            50.0,
            260.0,
            985.0,
            fill="#403434",
            outline="")
        # Tab option 1 buttons
        button_image_17 = PhotoImage(
            file=relative_to_assets("button_17.png"))
        button_17 = Button(
            image=button_image_17,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_17 clicked"),
            relief="flat"
        )
        button_17.place(
            x=173.0,
            y=60.0,
            width=30.0,
            height=30.0
        )
        button_image_18 = PhotoImage(
            file=relative_to_assets("button_18.png"))
        button_18 = Button(
            image=button_image_18,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_18 clicked"),
            relief="flat"
        )
        button_18.place(
            x=133.0,
            y=60.0,
            width=30.0,
            height=30.0
        )
        button_image_19 = PhotoImage(
            file=relative_to_assets("button_19.png"))
        button_19 = Button(
            image=button_image_19,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_19 clicked"),
            relief="flat"
        )
        button_19.place(
            x=93.0,
            y=60.0,
            width=30.0,
            height=30.0
        )
        # Tab option 1 GUI lines
        self.canvas.create_rectangle(
            42.0,
            100.0,
            53.0,
            101.0,
            fill="#8B8585",
            outline="")
        self.canvas.create_rectangle(
            62.0,
            100.0,
            73.0,
            101.0,
            fill="#8B8585",
            outline="")
        self.canvas.create_rectangle(
            82.0,
            100.0,
            93.0,
            101.0,
            fill="#8B8585",
            outline="")
        self.canvas.create_rectangle(
            102.0,
            100.0,
            113.0,
            101.0,
            fill="#8B8585",
            outline="")
        self.canvas.create_rectangle(
            122.0,
            100.0,
            133.0,
            101.0,
            fill="#8B8585",
            outline="")
        self.canvas.create_rectangle(
            142.0,
            100.0,
            153.0,
            101.0,
            fill="#8B8585",
            outline="")
        self.canvas.create_rectangle(
            162.0,
            100.0,
            173.0,
            101.0,
            fill="#8B8585",
            outline="")
        self.canvas.create_rectangle(
            182.0,
            100.0,
            193.0,
            101.0,
            fill="#8B8585",
            outline="")
        self.canvas.create_rectangle(
            182.0,
            100.0,
            193.0,
            101.0,
            fill="#8B8585",
            outline="")
        self.canvas.create_rectangle(
            202.0,
            100.0,
            213.0,
            101.0,
            fill="#8B8585",
            outline="")
        self.canvas.create_rectangle(
            222.0,
            100.0,
            233.0,
            101.0,
            fill="#8B8585",
            outline="")
        self.canvas.create_rectangle(
            242.0,
            100.0,
            253.0,
            101.0,
            fill="#8B8585",
            outline="")
        # Tab option 1 text
        self.canvas.create_text(
            50.0,
            110.0,
            anchor="nw",
            text="Files found:",
            fill="#FFFFFF",
            font=("Inter Bold", 12 * -1)
        )
        
        # Tab option 3
        self.canvas.create_rectangle(
            30.0,
            20.0,
            260.0,
            50.0,
            fill="#232020",
            outline="")
        self.canvas.create_rectangle(
            184.0,
            25.0,
            235.0,
            47.0,
            fill="#342B2B",
            outline="")
        self.canvas.create_rectangle(
            182.0,
            26.0,
            237.0,
            48.0,
            fill="#342B2B",
            outline="")
        button_image_20 = PhotoImage(
            file=relative_to_assets("button_20.png"))
        button_20 = Button(
            image=button_image_20,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_20 clicked"),
            relief="flat"
        )
        button_20.place(
            x=180.0,
            y=28.0,
            width=59.0,
            height=22.0
        )
    
        # Tab options 2
        self.canvas.create_rectangle(
            123.0,
            25.0,
            174.0,
            47.0,
            fill="#342B2B",
            outline=""
        )
        self.canvas.create_rectangle(
            121.0,
            26.0,
            176.0,
            48.0,
            fill="#342B2B",
            outline=""
        )
        button_image_21 = PhotoImage(
            file=relative_to_assets("button_21.png"))
        button_21 = Button(
            image=button_image_21,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_21 clicked"),
            relief="flat"
        )
        button_21.place(
            x=119.0,
            y=28.0,
            width=59.0,
            height=22.0
        )
        # Tab option 1
        self.canvas.create_rectangle(
            62.0,
            25.0,
            113.0,
            47.0,
            fill="#413535",
            outline=""
        )
        self.canvas.create_rectangle(
            60.0,
            26.0,
            115.0,
            48.0,
            fill="#413535",
            outline=""
        )
        button_image_22 = PhotoImage(
            file=relative_to_assets("button_22.png"))
        button_22 = Button(
            image=button_image_22,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_22 clicked"),
            relief="flat"
        )
        
        button_22.place(
            x=58.0,
            y=28.0,
            width=59.0,
            height=22.0
        )

class Decorative():
    def __init__(self, canvas):
        # Using the global object
        self.canvas = canvas

        # Seperator left high bar
        self.canvas.create_rectangle(
            30.0,
            50.0,
            36.0,
            985.0,
            fill="#524C4C",
            outline="")

        # Title
        self.canvas.create_text(
            599.0,
            0.0,
            anchor="nw",
            text="Melody-Annotator v0.00.1 | Directory: Dir",
            fill="#FFFFFF",
            font=("Inter Bold", 12 * -1)
        )

        # GUI Lines
        self.canvas.create_rectangle(
            1348.0,
            44.0,
            1349.0,
            50.0,
            fill="#8B8585",
            outline="")

        self.canvas.create_rectangle(
            1348.0,
            36.0,
            1349.0,
            42.0,
            fill="#8B8585",
            outline="")

        self.canvas.create_rectangle(
            1348.0,
            27.0,
            1349.0,
            33.0,
            fill="#8B8585",
            outline="")

        self.canvas.create_rectangle(
            1348.0,
            19.0,
            1349.0,
            25.0,
            fill="#8B8585",
            outline="")

        self.canvas.create_rectangle(
            299.0,
            46.0,
            300.0,
            50.0,
            fill="#8B8585",
            outline="")

        self.canvas.create_rectangle(
            299.0,
            38.0,
            300.0,
            44.0,
            fill="#8B8585",
            outline="")

        self.canvas.create_rectangle(
            299.0,
            33.0,
            300.0,
            37.0,
            fill="#8B8585",
            outline="")

        self.canvas.create_rectangle(
            299.0,
            26.0,
            300.0,
            32.0,
            fill="#8B8585",
            outline="")

        self.canvas.create_rectangle(
            299.0,
            19.0,
            300.0,
            24.0,
            fill="#8B8585",
            outline="")

if __name__ == "__main__":
    window = Tk()

    window.geometry("1440x1024")
    window.configure(bg = "#FFFFFF")
    
    # Canavs of app
    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 1024,
        width = 1440,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    a = app(canvas)
    b = textLoader(canvas)
    c = sidebar(canvas)
    d = tabOptions(canvas)
    e = Decorative(canvas)
    
    # Configuring the app's window
    window.resizable(False, False)              # My standards has made by defy it.
    window.mainloop()